[versions]

# Plugins
agp = "9.2.1"
kotlin = "2.3.21"
protobuf = "0.10.0"
ksp = "2.3.9"

coreKtx = "1.18.0"
appcompat = "1.7.1"
material = "1.14.0"

# LSParanoid
lsparanoid = "0.6.0"

# okhttp3
okhttp = "5.3.2"

# Xposed
xposed = "101.0.1"
xpHelper = "ad6196f73d"

# ByteBuddy
byteBuddy = "1.18.8"

# ProtoBuf
protobuf-javalite = "4.34.1"
kotlinx-serialization = "1.11.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# LSParanoid
lsparanoid = { group = "org.lsposed.lsparanoid", name = "gradle-plugin", version.ref = "lsparanoid" }

# okhttp3
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# Xposed
xposed-api = { module = "io.github.libxposed:api", version.ref = "xposed" }
xphelper = { group = "com.github.relimus", name = "XPHelper", version.ref = "xpHelper" }

# BytyBuddy-Android
byte-buddy-android = { group = "net.bytebuddy", name = "byte-buddy-android", version.ref = "byteBuddy" }

# KSP
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# ProtoBuf
protobuf-java-lite = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-javalite" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
